name: sync

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Fetch'
      run: |
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/Magic-Suite-NX/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o AIO.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/arcane/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o arcane.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/EdiZon-Overlay/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o EdiZon-Overlay.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/FanControl/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o FanControl.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/FPSLocker/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o FPSLocker.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/JKSV-webDAV/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o JKSV-webDAV.zip

        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/Guides/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o package_Guides.zip        
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/Magic/releases/latest | jq '.assets' | jq '.[1].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o package_Magic.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/R2Config/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o package_R2Config.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/Settings/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o package_Settings.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/Updater/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o package_Updater.zip

        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/ReverseNX-RT/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o ReverseNX-RT.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/SaltyNX/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o SaltyNX.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/Status-Monitor-Overlay/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o Status-Monitor-Overlay.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/sys-clk-oc/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o sys-clk-oc.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/ultracam/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o ultracam.zip
        
        curl -sL https://github.com/WE1ZARD/wiliwili/releases/download/latest/wiliwili.zip -o wiliwili.zip
        
    - name: 'Release'
      uses: softprops/action-gh-release@master
      with:
        body: 'fetch every 6 hours'
        tag_name: 'latest'
        files: |
          AIO.zip
          arcane.zip
          EdiZon-Overlay.zip
          FanControl.zip
          FPSLocker.zip
          JKSV-webDAV.zip
          package_Guides.zip 
          package_Magic.zip
          package_Settings.zip
          package_Updater.zip
          package_R2Config.zip
          ReverseNX-RT.zip
          SaltyNX.zip
          Status-Monitor-Overlay.zip
          sys-clk-oc.zip
          ultracam.zip
          wiliwili.zip